const MEALS_LIST = [
  {
    hotel_id: "h1",
    hotel_name: "Kerla Restaurent",
    dishes: [
      {
        id: "m1",
        name: "Mutton Curry",
        price: 300,
        discount: 20,
        veg: true,
        url: "https://c.ndtvimg.com/2020-07/kr6cq19_paneer_625x300_14_July_20.jpg",
        description: "",
        hotel_name: "Kerla Restaurent",
      },
      {
        id: "m2",
        name: "Butter Chicken",
        price: 500,
        discount: 25,
        veg: false,
        url: "https://c.ndtvimg.com/2020-07/kr6cq19_paneer_625x300_14_July_20.jpg",
        description: "",
        hotel_name: "Kerla Restaurent",
      },
      {
        id: "m3",
        name: "Chicken Lababdar",
        price: 260,
        discount: 20,
        veg: false,
        url: "https://c.ndtvimg.com/2020-07/kr6cq19_paneer_625x300_14_July_20.jpg",
        description: "",
        hotel_name: "Kerla Restaurent",
      },
      {
        id: "m4",
        name: "Chilly Baby Corn",
        price: 180,
        discount: 10,
        veg: true,
        url: "https://c.ndtvimg.com/2020-07/kr6cq19_paneer_625x300_14_July_20.jpg",
        description: "",
        hotel_name: "Kerla Restaurent",
      },
      {
        id: "m5",
        name: "Crispy Veg",
        price: 180,
        discount: 15,
        veg: true,
        url: "https://c.ndtvimg.com/2020-07/kr6cq19_paneer_625x300_14_July_20.jpg",
        description: "",
        hotel_name: "Kerla Restaurent",
      },
      {
        id: "m6",
        name: "Desi Murg Masala",
        price: 1200,
        discount: 10,
        veg: false,
        url: "https://c.ndtvimg.com/2020-07/kr6cq19_paneer_625x300_14_July_20.jpg",
        description: "",
        hotel_name: "Kerla Restaurent",
      },
    ],
  },
  {
    hotel_id: "h2",
    hotel_name: "Sidharth Family Restaurent",
    dishes: [
      {
        id: "m7",
        name: "Chicken Hydrabadi",
        price: 200,
        discount: 20,
        veg: false,
        url: "https://c.ndtvimg.com/2020-07/kr6cq19_paneer_625x300_14_July_20.jpg",
        description: "",
        hotel_name: "Sidharth Family Restaurent",
      },
      {
        id: "m8",
        name: "Chicken Tikka Masala",

        price: 220,
        discount: 20,
        veg: false,
        url: "https://c.ndtvimg.com/2020-07/kr6cq19_paneer_625x300_14_July_20.jpg",
        description: "",
        hotel_name: "Sidharth Family Restaurent",
      },
      {
        id: "m9",
        name: "Chicken Fry",

        price: 110,
        discount: 20,
        veg: false,
        url: "https://c.ndtvimg.com/2020-07/kr6cq19_paneer_625x300_14_July_20.jpg",
        description: "",
        hotel_name: "Sidharth Family Restaurent",
      },
      {
        id: "m10",
        name: "Chicken Burger",
        price: 180,
        discount: 20,
        veg: false,
        url: "https://c.ndtvimg.com/2020-07/kr6cq19_paneer_625x300_14_July_20.jpg",
        description: "",
        hotel_name: "Sidharth Family Restaurent",
      },
      {
        id: "m11",
        name: "Veg Burger",
        price: 180,
        discount: 10,
        veg: true,
        url: "https://c.ndtvimg.com/2020-07/kr6cq19_paneer_625x300_14_July_20.jpg",
        description: "",
        hotel_name: "Sidharth Family Restaurent",
      },
      {
        id: "m12",
        name: "Paneer Manchurian",
        price: 160,
        discount: 5,
        veg: true,
        url: "https://c.ndtvimg.com/2020-07/kr6cq19_paneer_625x300_14_July_20.jpg",
        description: "",
        hotel_name: "Sidharth Family Restaurent",
      },
    ],
  },
  {
    hotel_id: "h3",
    hotel_name: "Al Karim Chicken Center",
    dishes: [
      {
        id: "m13",
        name: "Mutton Biryani",
        price: 90,
        discount: 20,
        veg: false,
        url: "https://c.ndtvimg.com/2020-07/kr6cq19_paneer_625x300_14_July_20.jpg",
        description: "",
        hotel_name: "Al Karim Chicken Center",
      },
      {
        id: "m14",
        name: "Mutton Korma",
        price: 100,
        discount: 20,
        veg: false,
        url: "https://c.ndtvimg.com/2020-07/kr6cq19_paneer_625x300_14_July_20.jpg",
        description: "",
        hotel_name: "Al Karim Chicken Center",
      },
      {
        id: "m15",
        name: "Chicken Biryani",
        price: 70,
        discount: 20,
        veg: false,
        url: "https://c.ndtvimg.com/2020-07/kr6cq19_paneer_625x300_14_July_20.jpg",
        description: "",
        hotel_name: "Al Karim Chicken Center",
      },
      {
        id: "m16",
        name: "Rumali Roti",
        price: 10,
        discount: 10,
        veg: true,
        url: "https://c.ndtvimg.com/2020-07/kr6cq19_paneer_625x300_14_July_20.jpg",
        description: "",
        hotel_name: "Al Karim Chicken Center",
      },
      {
        id: "m17",
        name: "Shahi Paneer",
        price: 200,
        discount: 20,
        veg: true,
        url: "https://c.ndtvimg.com/2020-07/kr6cq19_paneer_625x300_14_July_20.jpg",
        description: "",
        hotel_name: "Kerla Restaurent",
      },
      {
        id: "m18",
        name: "Dal Fry",
        price: 90,
        discount: 10,
        veg: true,
        url: "https://c.ndtvimg.com/2020-07/kr6cq19_paneer_625x300_14_July_20.jpg",
        description: "",
        hotel_name: "Kerla Restaurent",
      },
    ],
  },
];

export default MEALS_LIST;
